#!/usr/bin/env python3
"""build_warren_home.py — wire live organs into the WARREN HOME player shell.

NON_SOVEREIGN | authority=false | sovereign=false | canon=false | ledger_effect=none

Reads the real organs:
  - temple/autoresearch/outbox/AR-*.json      → dreams (unconsumed proposals)
  - temple/autoresearch/consumption_log.ndjson → carnet + histoire (operator pen)
and emits apps/goblin-warren/warren_home_data.js — a static JS sidecar the
home HTML loads over file:// with no server.

LAW OF THE HOME
  - The home DISPLAYS organs; it cannot mark, admit, mutate, or grant anything.
    Dream shown ⊬ dream admitted · meter ⊬ state · SURFACE CANNOT MARK.
  - Meters are RENDERINGS of state, never state itself (garden skin law).
  - Deterministic: same organ bytes → same sidecar bytes. No wall clock,
    no randomness. --check re-derives and compares (local replay witness).
  - Fail-visible: broken pen chain or unreadable packet is surfaced in the
    payload, never hidden, never synthesized.

Usage:
  python3 apps/goblin-warren/build_warren_home.py           # (re)build
  python3 apps/goblin-warren/build_warren_home.py --check   # replay witness
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTBOX = REPO_ROOT / "temple" / "autoresearch" / "outbox"
DEFAULT_PEN_LOG = REPO_ROOT / "temple" / "autoresearch" / "consumption_log.ndjson"
DEFAULT_OUT = Path(__file__).resolve().parent / "warren_home_data.js"

sys.path.insert(0, str(REPO_ROOT / "temple" / "autoresearch"))
import operator_pen as pen  # noqa: E402

_SEVERITY = {"risk": "high", "test_gap": "medium", "proposal": "low",
             "doc_gap": "low", "quest_candidate": "low", "compost_candidate": "info"}


def _title(summary: str) -> str:
    s = " ".join((summary or "").split())
    for sep in (". ", " — ", "; ", ": "):
        if sep in s:
            s = s.split(sep, 1)[0] + ("" if sep == ". " else sep.strip())
            break
    return s[:72]


def build_payload(outbox: Path, log: Path) -> dict:
    entries = pen.read_log(log)
    chain_broken = pen.verify_chain(entries)
    eff = pen.effective_decisions(entries)
    packets = pen.load_packets(outbox)

    dreams, skipped = [], []
    for p in sorted(packets, key=lambda p: p["packet_id"]):
        if p["packet_id"] in eff:
            continue
        if p.get("finding_type") == "BAD_JSON":
            skipped.append({"packet_id": p["packet_id"], "why": "BAD_JSON"})
            continue
        dreams.append({
            "packet_id": p["packet_id"],
            "title": _title(str(p.get("summary", ""))),
            "finding_type": p.get("finding_type", "?"),
            "severity": _SEVERITY.get(p.get("finding_type", ""), "info"),
        })

    marks = [{"packet_id": e["packet_id"], "decision": e["decision"],
              "note": str(e.get("note", ""))[:110], "at": e.get("at", "")}
             for e in entries]
    counts = {"acted": 0, "rejected": 0, "deferred": 0}
    for e in eff.values():
        counts[e["decision"]] = counts.get(e["decision"], 0) + 1

    n_un = len(dreams)
    # Meters: RENDERINGS of organ state, never state itself. Formulas are
    # garden skin — bounded, deterministic, and labeled as such in the UI.
    meters = {
        "reves_badge": n_un,
        "confiance": min(100, 20 + 2 * len(eff)),          # trust accrues per mark
        "humeur": min(100, 30 + 10 * counts["acted"]),      # acted dreams cheer town
        "danger": min(100, 10 * n_un),                      # unconsumed pressure
        "ferraille": counts["rejected"],                    # composted scrap
        "nourriture": min(100, 25 + 5 * counts["acted"] + 2 * counts["deferred"]),
    }

    return {
        "schema": "WARREN_HOME_DATA_V1",
        "authority": False, "sovereign": False, "canon": False,
        "ledger_effect": "none",
        "surface_can_mark": False,
        "law": ("Les Gobelins rêvent. Vous décidez. — dream shown ⊬ dream admitted; "
                "meters are renderings of state, never state itself; "
                "marks happen only via operator_pen.py, never here."),
        "pen_chain": "BROKEN: " + chain_broken if chain_broken else "intact",
        "day": {"marks_total": len(eff), "counts": counts},
        "meters": meters,
        "dreams": dreams,
        "skipped": skipped,
        "carnet": marks[-8:][::-1],     # latest first
        "histoire": marks,              # full replayable mark timeline
        "start_day_command": ("python3 temple/autoresearch/autoresearch_scanner.py "
                              "--input-dir docs/proposals   # dry-run; crossings arrive as dreams"),
    }


def render_js(payload: dict) -> str:
    return ("// warren_home_data.js — GENERATED by build_warren_home.py. DO NOT EDIT.\n"
            "// NON_SOVEREIGN · authority=false · ledger_effect=none · "
            "surface cannot mark · dream ⊬ admission\n"
            "window.WARREN_HOME = "
            + json.dumps(payload, indent=1, ensure_ascii=False, sort_keys=True)
            + ";\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outbox", type=Path, default=DEFAULT_OUTBOX)
    ap.add_argument("--log", type=Path, default=DEFAULT_PEN_LOG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="replay witness: re-derive and compare on-disk sidecar")
    a = ap.parse_args()
    js = render_js(build_payload(a.outbox, a.log))
    if a.check:
        on_disk = a.out.read_text(encoding="utf-8") if a.out.exists() else ""
        if on_disk != js:
            print("❌ REPLAY MISMATCH: sidecar differs from re-derivation")
            return 1
        print("✅ replay witness: sidecar matches organs")
        return 0
    a.out.write_text(js, encoding="utf-8")
    print(f"built {a.out.name}: {len(js)} bytes · "
          f"dreams={js.count('packet_id') and 'see payload'} · surface_can_mark=false")
    return 0


if __name__ == "__main__":
    sys.exit(main())
