#!/usr/bin/env python3
"""build_warren_feed.py — wire real AUTORESEARCH outbox packets into WARREN TOWN.

NON_SOVEREIGN | authority=false | sovereign=false | canon=false | ledger_effect=none

Reads temple/autoresearch/outbox/AR-*.json (AUTORESEARCH_PACKET_V1) plus any
operator marks (triage/resolved/*_marked.json and, when present,
temple/autoresearch/consumption_log.ndjson) and emits
apps/goblin-warren/warren_town_feed.js — a static JS sidecar the town HTML
loads over file:// with no server.

LAW OF THE FEED
  - The feed DISPLAYS proposals; it cannot admit, mutate, or grant ZOL.
    NPC carries packet ⊬ packet admitted · garden mark ⊬ kernel admission.
  - Deterministic: same outbox bytes → same feed bytes. No wall clock, no
    randomness anywhere in the output. --check re-derives and compares the
    on-disk feed (a local replay witness).
  - Fail-visible: an unreadable packet lands in feed.skipped as BAD_JSON —
    never silently dropped, never synthesized.
  - HAL carries nothing. HAL is a lantern, not a courier.

Usage:
  python3 apps/goblin-warren/build_warren_feed.py           # (re)build feed
  python3 apps/goblin-warren/build_warren_feed.py --check   # replay witness
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTBOX = REPO_ROOT / "temple" / "autoresearch" / "outbox"
DEFAULT_RESOLVED = REPO_ROOT / "temple" / "autoresearch" / "triage" / "resolved"
DEFAULT_PEN_LOG = REPO_ROOT / "temple" / "autoresearch" / "consumption_log.ndjson"
DEFAULT_OUT = Path(__file__).resolve().parent / "warren_town_feed.js"

# finding_type → the role-bodies that carry it (round-robin, sorted packet order).
# HAL is never a courier: it lights verdicts, it does not carry proposals.
ROLE_GROUPS = {
    "risk": ["CLAW", "WARDEN", "JESTER"],
    "test_gap": ["WARDEN", "ARCHIVIST"],
    "proposal": ["GOBLIN", "CHIDDUSH", "STEWARD", "MAYOR", "HER"],
}
DEFAULT_GROUP = ["ARCHIVIST", "STEWARD"]

# finding_type → severity band (deterministic; bumped one step if risk_flags present).
_SEVERITY = {"risk": "high", "test_gap": "medium", "proposal": "low",
             "doc_gap": "low", "quest_candidate": "low", "compost_candidate": "info"}
_BUMP = {"info": "low", "low": "medium", "medium": "high", "high": "high"}


def _title(summary: str) -> str:
    """Stable, deterministic packet title: first sentence/clause of the summary,
    capped at 72 chars. No wall clock, no randomness."""
    s = " ".join((summary or "").split())
    for sep in (". ", " — ", " – ", "; ", ": "):
        if sep in s:
            s = s.split(sep, 1)[0]
            break
    return (s[:69] + "…") if len(s) > 72 else s or "(untitled)"

BANNER = (
    "/* WARREN_FEED_V0 — generated by apps/goblin-warren/build_warren_feed.py.\n"
    "   DO NOT HAND-EDIT — rebuild from the outbox instead.\n"
    "   NON_SOVEREIGN · authority=false · sovereign=false · ledger_effect=none\n"
    "   NPC carries ⊬ admits · garden mark ⊬ kernel admission · 📜 ledger sleeps */\n"
)


def load_marks(resolved_dir: Path, pen_log: Path) -> dict:
    """Operator marks, display-only. Pen log entries (the newer organ) win."""
    marks: dict = {}
    if resolved_dir.is_dir():
        for f in sorted(resolved_dir.glob("*_marked.json")):
            try:
                d = json.loads(f.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            pid = d.get("packet_id")
            if pid and d.get("decision"):
                marks[pid] = d["decision"]
    if pen_log.is_file():
        for line in pen_log.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            pid = d.get("packet_id")
            if pid and d.get("decision"):
                marks[pid] = d["decision"]
    return marks


def build_feed(outbox: Path, resolved_dir: Path, pen_log: Path) -> dict:
    marks = load_marks(resolved_dir, pen_log)
    digest = hashlib.sha256()
    packets, skipped = [], []
    for f in sorted(outbox.glob("AR-*.json")):
        raw = f.read_bytes()
        digest.update(f.name.encode("utf-8"))
        digest.update(raw)
        try:
            d = json.loads(raw)
        except json.JSONDecodeError as exc:
            skipped.append({"file": f.name, "reason": f"BAD_JSON: {exc.msg}"})
            continue
        prov = d.get("provenance") or {}
        ftype = d.get("finding_type", "unknown")
        summary = d.get("summary", "(no summary)")
        risk_flags = d.get("risk_flags") or []
        source_refs = d.get("source_refs") or []
        severity = _SEVERITY.get(ftype, "info")
        if risk_flags:
            severity = _BUMP[severity]
        packets.append(
            {
                "packet_id": d.get("packet_id", f.stem),
                "finding_type": ftype,
                "title": _title(summary),
                "summary": summary,
                "recommended_action": d.get("recommended_action", "?"),
                "proposer": prov.get("proposer", "unknown proposer"),
                "scanned_at": d.get("scanned_at", "?"),
                "mark": marks.get(d.get("packet_id"), None),
                # AAA feed fields — all display-only, never authority.
                "authority": False,
                "admission": "FORBIDDEN",
                "severity": severity,
                "proof_status": "grounded" if source_refs else "ungrounded",
                "replay_status": "in_digest",  # every kept packet contributes to source_digest
            }
        )

    roles: dict = {}
    counters: dict = {}
    for p in packets:  # already in sorted-filename order → deterministic
        group = ROLE_GROUPS.get(p["finding_type"], DEFAULT_GROUP)
        i = counters.get(p["finding_type"], 0)
        counters[p["finding_type"]] = i + 1
        roles.setdefault(group[i % len(group)], []).append(p)

    return {
        "schema": "WARREN_FEED_V0",
        "authority": False,
        "sovereign": False,
        "canon": False,
        "ledger_effect": "none",
        "source": "temple/autoresearch/outbox",
        "source_digest": digest.hexdigest(),
        "packet_count": len(packets),
        "skipped": skipped,
        "roles": roles,
    }


def render_js(feed: dict) -> str:
    body = json.dumps(feed, ensure_ascii=False, indent=2, sort_keys=True)
    return f"{BANNER}window.WarrenFeed = {body};\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--outbox", type=Path, default=DEFAULT_OUTBOX)
    ap.add_argument("--resolved", type=Path, default=DEFAULT_RESOLVED)
    ap.add_argument("--pen-log", type=Path, default=DEFAULT_PEN_LOG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument(
        "--check",
        action="store_true",
        help="replay witness: re-derive the feed and compare to the on-disk file",
    )
    args = ap.parse_args(argv)

    if not args.outbox.is_dir():
        print(f"FAIL_CLOSED: outbox not found: {args.outbox}", file=sys.stderr)
        return 2

    feed = build_feed(args.outbox, args.resolved, args.pen_log)
    js = render_js(feed)

    if args.check:
        if not args.out.is_file():
            print(f"CHECK FAIL: feed missing on disk: {args.out}", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != js:
            print("CHECK FAIL: on-disk feed does not replay from the outbox", file=sys.stderr)
            return 1
        print(f"CHECK PASS: {args.out.name} replays from outbox bytes")
        return 0

    args.out.write_text(js, encoding="utf-8")
    print(
        f"wrote {args.out} · {feed['packet_count']} packets · "
        f"{len(feed['skipped'])} skipped · digest {feed['source_digest'][:12]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
